"""opponent negotiation: datetime, country, proposals, messages

Revision ID: 017026865044
Revises: 5d4a13b18e8a
Create Date: 2026-07-26 14:49:54.377877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017026865044'
down_revision: Union[str, Sequence[str], None] = '5d4a13b18e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiation_messages',
    sa.Column('opponent_application_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opponent_application_id'], ['opponent_applications.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_messages_opponent_application_id'), 'negotiation_messages', ['opponent_application_id'], unique=False)
    op.alter_column('matches', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('opponent_applications', sa.Column('proposed_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('opponent_applications', sa.Column('proposed_pitch', sa.String(length=255), nullable=True))
    op.add_column('opponent_applications', sa.Column('proposed_by_team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'opponent_applications', 'teams', ['proposed_by_team_id'], ['id'])
    op.add_column('opponent_searches', sa.Column('country', sa.String(length=60), nullable=True))
    op.alter_column('opponent_searches', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_opponent_searches_country'), 'opponent_searches', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opponent_searches_country'), table_name='opponent_searches')
    op.alter_column('opponent_searches', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('opponent_searches', 'country')
    op.drop_constraint(None, 'opponent_applications', type_='foreignkey')
    op.drop_column('opponent_applications', 'proposed_by_team_id')
    op.drop_column('opponent_applications', 'proposed_pitch')
    op.drop_column('opponent_applications', 'proposed_date')
    op.alter_column('matches', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_negotiation_messages_opponent_application_id'), table_name='negotiation_messages')
    op.drop_table('negotiation_messages')
    # ### end Alembic commands ###
