"""Add pitch catalog and booked_by_team_id to negotiation

Revision ID: 134dd592cece
Revises: e222e09c0502
Create Date: 2026-07-28 11:05:24.317087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134dd592cece'
down_revision: Union[str, Sequence[str], None] = 'e222e09c0502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('price_per_hour', sa.Float(), nullable=True),
    sa.Column('is_neutral', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitches_team_id'), 'pitches', ['team_id'], unique=False)

    # matches.booked_by_team_id and negotiation_proposals.booked_by_team_id are NOT NULL, but
    # existing rows predate the column — add nullable, backfill with a sensible default (the
    # existing negotiation convention: whoever proposed the terms books the pitch), then tighten.
    op.add_column('matches', sa.Column('booked_by_team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'matches', 'teams', ['booked_by_team_id'], ['id'])
    op.execute('UPDATE matches SET booked_by_team_id = team_a_id WHERE booked_by_team_id IS NULL')
    op.alter_column('matches', 'booked_by_team_id', nullable=False)

    op.add_column('negotiation_proposals', sa.Column('booked_by_team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'negotiation_proposals', 'teams', ['booked_by_team_id'], ['id'])
    op.execute(
        'UPDATE negotiation_proposals SET booked_by_team_id = proposed_by_team_id '
        'WHERE booked_by_team_id IS NULL'
    )
    op.alter_column('negotiation_proposals', 'booked_by_team_id', nullable=False)

    op.add_column('opponent_applications', sa.Column('proposed_booked_by_team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'opponent_applications', 'teams', ['proposed_booked_by_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opponent_applications', type_='foreignkey')
    op.drop_column('opponent_applications', 'proposed_booked_by_team_id')
    op.drop_constraint(None, 'negotiation_proposals', type_='foreignkey')
    op.drop_column('negotiation_proposals', 'booked_by_team_id')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'booked_by_team_id')
    op.drop_index(op.f('ix_pitches_team_id'), table_name='pitches')
    op.drop_table('pitches')
    # ### end Alembic commands ###
