"""add location fields to player_availabilities

Revision ID: 183a1ae81029
Revises: f27b6e0a3c9d
Create Date: 2026-07-25 12:57:31.659424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183a1ae81029'
down_revision: Union[str, Sequence[str], None] = 'f27b6e0a3c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_availabilities', sa.Column('region', sa.String(length=120), nullable=True))
    op.add_column('player_availabilities', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('player_availabilities', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('player_availabilities', sa.Column('radius_km', sa.Float(), nullable=True))
    op.create_index(op.f('ix_player_availabilities_region'), 'player_availabilities', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_availabilities_region'), table_name='player_availabilities')
    op.drop_column('player_availabilities', 'radius_km')
    op.drop_column('player_availabilities', 'longitude')
    op.drop_column('player_availabilities', 'latitude')
    op.drop_column('player_availabilities', 'region')
    # ### end Alembic commands ###
