"""add country to player_availabilities

Revision ID: 20e6566fe640
Revises: d81774eed8f3
Create Date: 2026-07-25 14:16:27.032914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e6566fe640'
down_revision: Union[str, Sequence[str], None] = 'd81774eed8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_availabilities', sa.Column('country', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_player_availabilities_country'), 'player_availabilities', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_availabilities_country'), table_name='player_availabilities')
    op.drop_column('player_availabilities', 'country')
    # ### end Alembic commands ###
