"""add lineup_position and roster country

Revision ID: 5d4a13b18e8a
Revises: 20e6566fe640
Create Date: 2026-07-26 13:59:08.814832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4a13b18e8a'
down_revision: Union[str, Sequence[str], None] = '20e6566fe640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roster_searches', sa.Column('country', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_roster_searches_country'), 'roster_searches', ['country'], unique=False)
    op.add_column('team_memberships', sa.Column('lineup_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_memberships', 'lineup_position')
    op.drop_index(op.f('ix_roster_searches_country'), table_name='roster_searches')
    op.drop_column('roster_searches', 'country')
    # ### end Alembic commands ###
