"""Add negotiation proposal history and time range/pitch address

Revision ID: 8ae5c3cca653
Revises: 017026865044
Create Date: 2026-07-27 11:31:11.260474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae5c3cca653'
down_revision: Union[str, Sequence[str], None] = '017026865044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiation_proposals',
    sa.Column('opponent_application_id', sa.UUID(), nullable=False),
    sa.Column('proposed_by_team_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pitch', sa.String(length=255), nullable=False),
    sa.Column('pitch_address', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opponent_application_id'], ['opponent_applications.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_proposals_opponent_application_id'), 'negotiation_proposals', ['opponent_application_id'], unique=False)
    op.add_column('opponent_applications', sa.Column('proposed_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('opponent_applications', sa.Column('proposed_pitch_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opponent_applications', 'proposed_pitch_address')
    op.drop_column('opponent_applications', 'proposed_end_date')
    op.drop_index(op.f('ix_negotiation_proposals_opponent_application_id'), table_name='negotiation_proposals')
    op.drop_table('negotiation_proposals')
    # ### end Alembic commands ###
