"""initial schema

Revision ID: 9a72b3e127e9
Revises: 
Create Date: 2026-07-22 14:16:21.434304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a72b3e127e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_types',
    sa.Column('sport', sa.Enum('SOCCER', 'TENNIS', 'PADDLE', name='sport', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'label', name='uq_game_type_sport_label')
    )
    op.create_table('reports',
    sa.Column('reporter_type', sa.Enum('USER', 'TEAM', name='partytype', native_enum=False, length=8), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_type', sa.Enum('USER', 'TEAM', name='partytype', native_enum=False, length=8), nullable=False),
    sa.Column('reported_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='reportstatus', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('sport', sa.Enum('SOCCER', 'TENNIS', 'PADDLE', name='sport', native_enum=False, length=32), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('is_adhoc', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('credit_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('PUBLISH_CHARGE', 'REFUND_NONENGAGEMENT', 'TOPUP', 'PURCHASE', name='creditreason', native_enum=False, length=32), nullable=False),
    sa.Column('related_search_type', sa.Enum('ROSTER_SEARCH', 'OPPONENT_SEARCH', 'GUEST_SEARCH', 'PLAYER_AVAILABILITY', name='searchtype', native_enum=False, length=32), nullable=True),
    sa.Column('related_search_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('opponent_searches',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('sport', sa.Enum('SOCCER', 'TENNIS', 'PADDLE', name='sport', native_enum=False, length=32), nullable=False),
    sa.Column('game_type_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('pitch', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CONFIRMED', 'WITHDRAWN', 'EXPIRED', name='listingstatus', native_enum=False, length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opponent_searches_city'), 'opponent_searches', ['city'], unique=False)
    op.create_index(op.f('ix_opponent_searches_team_id'), 'opponent_searches', ['team_id'], unique=False)
    op.create_table('player_availabilities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sport', sa.Enum('SOCCER', 'TENNIS', 'PADDLE', name='sport', native_enum=False, length=32), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CONFIRMED', 'WITHDRAWN', 'EXPIRED', name='listingstatus', native_enum=False, length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_availabilities_city'), 'player_availabilities', ['city'], unique=False)
    op.create_index(op.f('ix_player_availabilities_user_id'), 'player_availabilities', ['user_id'], unique=False)
    op.create_table('roster_searches',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CONFIRMED', 'WITHDRAWN', 'EXPIRED', name='listingstatus', native_enum=False, length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roster_searches_city'), 'roster_searches', ['city'], unique=False)
    op.create_index(op.f('ix_roster_searches_team_id'), 'roster_searches', ['team_id'], unique=False)
    op.create_table('team_memberships',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('CAPTAIN', 'ADMIN', 'MEMBER', name='teamrole', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LEFT', name='membershipstatus', native_enum=False, length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_membership_team_user')
    )
    op.create_index(op.f('ix_team_memberships_team_id'), 'team_memberships', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_memberships_user_id'), 'team_memberships', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('opponent_search_id', sa.UUID(), nullable=False),
    sa.Column('team_a_id', sa.UUID(), nullable=False),
    sa.Column('team_b_id', sa.UUID(), nullable=False),
    sa.Column('sport', sa.Enum('SOCCER', 'TENNIS', 'PADDLE', name='sport', native_enum=False, length=32), nullable=False),
    sa.Column('game_type_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('pitch', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED_BY_A', 'CANCELLED_BY_B', 'PLAYED', name='matchstatus', native_enum=False, length=24), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.id'], ),
    sa.ForeignKeyConstraint(['opponent_search_id'], ['opponent_searches.id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_team_a_id'), 'matches', ['team_a_id'], unique=False)
    op.create_index(op.f('ix_matches_team_b_id'), 'matches', ['team_b_id'], unique=False)
    op.create_table('opponent_applications',
    sa.Column('opponent_search_id', sa.UUID(), nullable=False),
    sa.Column('responding_team_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DECLINED', 'WITHDRAWN', name='applicationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opponent_search_id'], ['opponent_searches.id'], ),
    sa.ForeignKeyConstraint(['responding_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opponent_applications_opponent_search_id'), 'opponent_applications', ['opponent_search_id'], unique=False)
    op.create_index(op.f('ix_opponent_applications_responding_team_id'), 'opponent_applications', ['responding_team_id'], unique=False)
    op.create_table('roster_applications',
    sa.Column('roster_search_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('PLAYER_APPLIED', 'TEAM_INVITED', name='applicationdirection', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DECLINED', 'WITHDRAWN', name='applicationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roster_search_id'], ['roster_searches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roster_applications_roster_search_id'), 'roster_applications', ['roster_search_id'], unique=False)
    op.create_index(op.f('ix_roster_applications_team_id'), 'roster_applications', ['team_id'], unique=False)
    op.create_index(op.f('ix_roster_applications_user_id'), 'roster_applications', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('context', sa.Enum('OPPONENT', 'HOST_GUEST', name='feedbackcontext', native_enum=False, length=16), nullable=False),
    sa.Column('from_type', sa.Enum('USER', 'TEAM', name='partytype', native_enum=False, length=8), nullable=False),
    sa.Column('from_id', sa.UUID(), nullable=False),
    sa.Column('to_type', sa.Enum('USER', 'TEAM', name='partytype', native_enum=False, length=8), nullable=False),
    sa.Column('to_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_match_id'), 'feedback', ['match_id'], unique=False)
    op.create_table('guest_searches',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CONFIRMED', 'WITHDRAWN', 'EXPIRED', name='listingstatus', native_enum=False, length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_searches_city'), 'guest_searches', ['city'], unique=False)
    op.create_index(op.f('ix_guest_searches_match_id'), 'guest_searches', ['match_id'], unique=False)
    op.create_index(op.f('ix_guest_searches_team_id'), 'guest_searches', ['team_id'], unique=False)
    op.create_table('disputes',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('raised_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED_REMOVED', 'RESOLVED_UPHELD', name='disputestatus', native_enum=False, length=24), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_feedback_id'), 'disputes', ['feedback_id'], unique=False)
    op.create_table('guest_applications',
    sa.Column('guest_search_id', sa.UUID(), nullable=True),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('PLAYER_APPLIED', 'TEAM_INVITED', name='applicationdirection', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DECLINED', 'WITHDRAWN', name='applicationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_search_id'], ['guest_searches.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_applications_guest_search_id'), 'guest_applications', ['guest_search_id'], unique=False)
    op.create_index(op.f('ix_guest_applications_match_id'), 'guest_applications', ['match_id'], unique=False)
    op.create_index(op.f('ix_guest_applications_team_id'), 'guest_applications', ['team_id'], unique=False)
    op.create_index(op.f('ix_guest_applications_user_id'), 'guest_applications', ['user_id'], unique=False)
    op.create_table('match_guest_participants',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('guest_application_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_application_id'], ['guest_applications.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_guest_participants_match_id'), 'match_guest_participants', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_guest_participants_team_id'), 'match_guest_participants', ['team_id'], unique=False)
    op.create_index(op.f('ix_match_guest_participants_user_id'), 'match_guest_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_guest_participants_user_id'), table_name='match_guest_participants')
    op.drop_index(op.f('ix_match_guest_participants_team_id'), table_name='match_guest_participants')
    op.drop_index(op.f('ix_match_guest_participants_match_id'), table_name='match_guest_participants')
    op.drop_table('match_guest_participants')
    op.drop_index(op.f('ix_guest_applications_user_id'), table_name='guest_applications')
    op.drop_index(op.f('ix_guest_applications_team_id'), table_name='guest_applications')
    op.drop_index(op.f('ix_guest_applications_match_id'), table_name='guest_applications')
    op.drop_index(op.f('ix_guest_applications_guest_search_id'), table_name='guest_applications')
    op.drop_table('guest_applications')
    op.drop_index(op.f('ix_disputes_feedback_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_guest_searches_team_id'), table_name='guest_searches')
    op.drop_index(op.f('ix_guest_searches_match_id'), table_name='guest_searches')
    op.drop_index(op.f('ix_guest_searches_city'), table_name='guest_searches')
    op.drop_table('guest_searches')
    op.drop_index(op.f('ix_feedback_match_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_roster_applications_user_id'), table_name='roster_applications')
    op.drop_index(op.f('ix_roster_applications_team_id'), table_name='roster_applications')
    op.drop_index(op.f('ix_roster_applications_roster_search_id'), table_name='roster_applications')
    op.drop_table('roster_applications')
    op.drop_index(op.f('ix_opponent_applications_responding_team_id'), table_name='opponent_applications')
    op.drop_index(op.f('ix_opponent_applications_opponent_search_id'), table_name='opponent_applications')
    op.drop_table('opponent_applications')
    op.drop_index(op.f('ix_matches_team_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_team_a_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_team_memberships_user_id'), table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_team_id'), table_name='team_memberships')
    op.drop_table('team_memberships')
    op.drop_index(op.f('ix_roster_searches_team_id'), table_name='roster_searches')
    op.drop_index(op.f('ix_roster_searches_city'), table_name='roster_searches')
    op.drop_table('roster_searches')
    op.drop_index(op.f('ix_player_availabilities_user_id'), table_name='player_availabilities')
    op.drop_index(op.f('ix_player_availabilities_city'), table_name='player_availabilities')
    op.drop_table('player_availabilities')
    op.drop_index(op.f('ix_opponent_searches_team_id'), table_name='opponent_searches')
    op.drop_index(op.f('ix_opponent_searches_city'), table_name='opponent_searches')
    op.drop_table('opponent_searches')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('reports')
    op.drop_table('game_types')
    # ### end Alembic commands ###
