"""Add gender to users

Revision ID: c336a7c1227e
Revises: 8ae5c3cca653
Create Date: 2026-07-27 13:45:50.154150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c336a7c1227e'
down_revision: Union[str, Sequence[str], None] = '8ae5c3cca653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', name='gender', native_enum=False, length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
