"""Add locale to users

Revision ID: e222e09c0502
Revises: c336a7c1227e
Create Date: 2026-07-27 15:01:36.460741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e222e09c0502'
down_revision: Union[str, Sequence[str], None] = 'c336a7c1227e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'locale',
            sa.Enum('en', 'fr', 'ar', name='locale', native_enum=False, length=8),
            nullable=False,
            server_default='en',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###
